package com.map.mapmaxv1.dto;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.map.mapmaxv1.dto.MarkDTO;

import com.map.mapmaxv1.dto.MarkDTODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig markDTODaoConfig;

    private final MarkDTODao markDTODao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        markDTODaoConfig = daoConfigMap.get(MarkDTODao.class).clone();
        markDTODaoConfig.initIdentityScope(type);

        markDTODao = new MarkDTODao(markDTODaoConfig, this);

        registerDao(MarkDTO.class, markDTODao);
    }
    
    public void clear() {
        markDTODaoConfig.clearIdentityScope();
    }

    public MarkDTODao getMarkDTODao() {
        return markDTODao;
    }

}
